# AtomMan LAMMPS atom_data

**Lucas M. Hale**, [lucas.hale@nist.gov](mailto:lucas.hale@nist.gov?Subject=ipr-demo), *Materials Science and Engineering Division, NIST*.

**Chandler A. Becker**, [chandler.becker@nist.gov](mailto:chandler.becker@nist.gov?Subject=ipr-demo), *Materials Science and Engineering Division, NIST*.

**Zachary T. Trautt**, [zachary.trautt@nist.gov](mailto:zachary.trautt@nist.gov?Subject=ipr-demo), *Materials Measurement Science Division, NIST*.

Version: 2016-03-31

[Disclaimers](http://www.nist.gov/public_affairs/disclaimer.cfm)

Return to the [main atomman page](https://github.com/usnistgov/atomman).

## Introduction

The atomman package was designed to allow for the creation and analysis of large scale atomistic simulations.  To help facilitate this, the atomman.lammps module contains a number of useful functions and classes that allow for atomman to interact with the LAMMPS molecular dynamics software.

Interactions with LAMMPS atom data files is handled with the atomman.lammps.atom_data module.  This module contains two functions, load and dump, that allow for data files to be read into atomman and written to a file, respectively. 

The underlying code can be found in [atomman/lammps/atom_data.py](https://github.com/usnistgov/atomman/blob/master/atomman/lammps/atom_data.py).

- - -

__Library Imports__

In [1]:
import os
import atomman as am
import atomman.lammps as lmp
import numpy as np

In [2]:
#create small demonstration system (GaAs unit cell)
prop_dict = {'atype': [1, 1, 1, 1, 2, 2, 2, 2],
             'pos':  [[0.00, 0.00, 0.00],
                      [0.50, 0.00, 0.50],
                      [0.50, 0.50, 0.00],
                      [0.00, 0.50, 0.50],
                      [0.25, 0.25, 0.25],
                      [0.75, 0.75, 0.25],
                      [0.25, 0.75, 0.75],
                      [0.75, 0.25, 0.75]]}

atoms = am.Atoms(natoms=8, prop=prop_dict)
box = am.Box(a=5.65, b=5.65, c=5.65)
system = am.System(box=box, atoms=atoms, scale=True)
print system.box
print system.atoms

avect =  [ 5.650,  0.000,  0.000]
bvect =  [ 0.000,  5.650,  0.000]
cvect =  [ 0.000,  0.000,  5.650]
origin = [ 0.000,  0.000,  0.000]
     id |   atype |  pos[0] |  pos[1] |  pos[2]
      0 |       1 |   0.000 |   0.000 |   0.000
      1 |       1 |   2.825 |   0.000 |   2.825
      2 |       1 |   2.825 |   2.825 |   0.000
      3 |       1 |   0.000 |   2.825 |   2.825
      4 |       2 |   1.413 |   1.413 |   1.413
      5 |       2 |   4.238 |   4.238 |   1.413
      6 |       2 |   1.413 |   4.238 |   4.238
      7 |       2 |   4.238 |   1.413 |   4.238


## 1. atom_data.dump()

The atom_data.dump() function writes a system's information to a LAMMPS atom data style file. The function arguments are:

- __fname__ = name (and location) of the file to write to. Required.

- __system__ = the atomman.System to extract values from. Required.

- __units__ = the LAMMPS units style associated with the atom data file. Default is 'metal'.
 
- __atom_style__ = the LAMMPS atom_style format associated with the atom data file. Default is 'atomic'.

In addition to creating the data file, the function will also return a string containing the LAMMPS input command lines associated with having LAMMPS properly read in the data file.

In [3]:
#write system to a atom data file
read_info = lmp.atom_data.dump('test.data', system, units='metal', atom_style='atomic')

#show the returned string of LAMMPS input commands
print read_info

#Script and atom data file prepared by AtomMan package

units metal
atom_style atomic
boundary p p p 
read_data test.data


In [4]:
#show the contents of test.data
with open('test.data') as f:
    print f.read()


8 atoms
2 atom types
0.000000 5.650000 xlo xhi
0.000000 5.650000 ylo yhi
0.000000 5.650000 zlo zhi

Atoms

1 1 0.0000000000000e+00 0.0000000000000e+00 0.0000000000000e+00
2 1 2.8250000000000e+00 0.0000000000000e+00 2.8250000000000e+00
3 1 2.8250000000000e+00 2.8250000000000e+00 0.0000000000000e+00
4 1 0.0000000000000e+00 2.8250000000000e+00 2.8250000000000e+00
5 2 1.4125000000000e+00 1.4125000000000e+00 1.4125000000000e+00
6 2 4.2375000000000e+00 4.2375000000000e+00 1.4125000000000e+00
7 2 1.4125000000000e+00 4.2375000000000e+00 4.2375000000000e+00
8 2 4.2375000000000e+00 1.4125000000000e+00 4.2375000000000e+00



In [5]:
#units style 'nano' uses lengths in nm instead on angstrom.
read_info = lmp.atom_data.dump('test.data', system, units='nano')

#show the returned string of LAMMPS input commands
print read_info
print '--------------------------------------------------------------'

#show the contents of test.data
with open('test.data') as f:
    print f.read()

#Script and atom data file prepared by AtomMan package

units nano
atom_style atomic
boundary p p p 
read_data test.data
--------------------------------------------------------------

8 atoms
2 atom types
0.000000 0.565000 xlo xhi
0.000000 0.565000 ylo yhi
0.000000 0.565000 zlo zhi

Atoms

1 1 0.0000000000000e+00 0.0000000000000e+00 0.0000000000000e+00
2 1 2.8250000000000e-01 0.0000000000000e+00 2.8250000000000e-01
3 1 2.8250000000000e-01 2.8250000000000e-01 0.0000000000000e+00
4 1 0.0000000000000e+00 2.8250000000000e-01 2.8250000000000e-01
5 2 1.4125000000000e-01 1.4125000000000e-01 1.4125000000000e-01
6 2 4.2375000000000e-01 4.2375000000000e-01 1.4125000000000e-01
7 2 1.4125000000000e-01 4.2375000000000e-01 4.2375000000000e-01
8 2 4.2375000000000e-01 1.4125000000000e-01 4.2375000000000e-01



Other atom_styles require additional atom properties to be defined.  The current version requires that specific property names be used:

- __m_id__ = integer molecule-ID

- __q__ = charge on atom (charge units)
 
- __diameter__ = diameter for atom_style 'sphere' (distance units)

- __e_flag__ = boolean flag for atom_style 'ellipsoid' (0 or 1)

- __l_flag__ = boolean flag for atom_style 'line' (0 or 1)

- __t_flag__ = boolean flag for atom_style 'tri' (0 or 1)

- __b_flag__ = boolean flag for atom_style 'body' (0 or 1)

- __m_temp__ = molecule template-index for atom_style 'template'

- __a_temp__ = atom template index for atom_style 'template'

- __density__ = particle density (mass/distance^3 units)

- __mass__ = mass of particle for atom_style 'body' (mass units)

- __volume__ = volume of particle (distance^3 units)

- __mux, muy, muz__ = components of dipole moment of atom for atom_style 'dipole' (dipole units)

- __rho, e, cv__ = density, energy, heat capacity for atom_style 'meso' (None units)

- __spin__ = integer electron spin for atom_styles 'electron' and 'wavepacket'

- __eradius__ = electron radius or fixed-core radius for atom_styles 'electron' and 'wavepacket' (distance units)

- __e_id__ = etag integer ID of electron that each wavepacket belongs to for atom_style 'wavepacket'

- __cs_re, cs_im__ = real/imaginary parts of wavepacket coefficients for atom_style 'wavepacket'

- __K_radius, c_radius__ = kernel_radius and contact_radius for atom_style 'smd' (distance units)


In [6]:
#atom_style charge demo
system.atoms_prop(key='q', value=[-1., -1., -1., -1., 1., 1., 1., 1.])
read_info = lmp.atom_data.dump('test.data', system, atom_style='charge')

#show the returned string of LAMMPS input commands
print read_info
print '--------------------------------------------------------------'

#show the contents of test.data
with open('test.data') as f:
    print f.read()

#Script and atom data file prepared by AtomMan package

units metal
atom_style charge
boundary p p p 
read_data test.data
--------------------------------------------------------------

8 atoms
2 atom types
0.000000 5.650000 xlo xhi
0.000000 5.650000 ylo yhi
0.000000 5.650000 zlo zhi

Atoms

1 1 -1.0000000000000e+00 0.0000000000000e+00 0.0000000000000e+00 0.0000000000000e+00
2 1 -1.0000000000000e+00 2.8250000000000e+00 0.0000000000000e+00 2.8250000000000e+00
3 1 -1.0000000000000e+00 2.8250000000000e+00 2.8250000000000e+00 0.0000000000000e+00
4 1 -1.0000000000000e+00 0.0000000000000e+00 2.8250000000000e+00 2.8250000000000e+00
5 2 1.0000000000000e+00 1.4125000000000e+00 1.4125000000000e+00 1.4125000000000e+00
6 2 1.0000000000000e+00 4.2375000000000e+00 4.2375000000000e+00 1.4125000000000e+00
7 2 1.0000000000000e+00 1.4125000000000e+00 4.2375000000000e+00 4.2375000000000e+00
8 2 1.0000000000000e+00 4.2375000000000e+00 1.4125000000000e+00 4.2375000000000e+00



If a 'velocity' property is assigned to the atoms, then the velocity values will also be included in the data file.  Depending on the atom_style, other velocity properties may be required to be defined:

- __erval__ = electron radial velocity for atom_style 'electron' (velocity units)

- __ang-momentum__ = angular momentum for atom_style 'ellipsoid' (angular momentum units)

- __ang-velocity__ = angular velocity for atom_style 'sphere' (angular velocity units)


In [7]:
system.atoms_prop(key='velocity', value=np.random.rand(8,3))
read_info = lmp.atom_data.dump('test.data', system)

#show the returned string of LAMMPS input commands
print read_info
print '--------------------------------------------------------------'

#show the contents of test.data
with open('test.data') as f:
    print f.read()

#Script and atom data file prepared by AtomMan package

units metal
atom_style atomic
boundary p p p 
read_data test.data
--------------------------------------------------------------

8 atoms
2 atom types
0.000000 5.650000 xlo xhi
0.000000 5.650000 ylo yhi
0.000000 5.650000 zlo zhi

Atoms

1 1 0.0000000000000e+00 0.0000000000000e+00 0.0000000000000e+00
2 1 2.8250000000000e+00 0.0000000000000e+00 2.8250000000000e+00
3 1 2.8250000000000e+00 2.8250000000000e+00 0.0000000000000e+00
4 1 0.0000000000000e+00 2.8250000000000e+00 2.8250000000000e+00
5 2 1.4125000000000e+00 1.4125000000000e+00 1.4125000000000e+00
6 2 4.2375000000000e+00 4.2375000000000e+00 1.4125000000000e+00
7 2 1.4125000000000e+00 4.2375000000000e+00 4.2375000000000e+00
8 2 4.2375000000000e+00 1.4125000000000e+00 4.2375000000000e+00

Velocities

1 4.9460373552288e+01 7.8716646052462e+01 6.5232198040918e+01
2 5.0290690827310e+01 6.9090375522951e+01 3.5293844626566e+01
3 6.0984657545537e+01 5.6637945559969e+01 6.9530904896981e

## 2. atom_data.load()

The atom_data.load() function reads a LAMMPS atom data style file. The function arguments are:

- __fname__ = name (and location) of the file to read. Required.

- __pbc__ = three boolean values where True indicates that a corresponding system direction is periodic. Default is (True, True, True).

- __units__ = the LAMMPS units style associated with the atom data file. Default is 'metal'.
 
- __atom_style__ = the LAMMPS atom_style format associated with the atom data file. Default is 'atomic'.

The function will return an atomman.System containing all property values converted from the appropriate units.

In [8]:
system2 = lmp.atom_data.load('test.data', pbc=(True, True, True))
print "system2.box ->"
print system2.box
print
print "system2.atoms ->"
print system2.atoms
print
print "system2.atoms_prop(key='velocity') ->"
print system2.atoms_prop(key='velocity')

system2.box ->
avect =  [ 5.650,  0.000,  0.000]
bvect =  [ 0.000,  5.650,  0.000]
cvect =  [ 0.000,  0.000,  5.650]
origin = [ 0.000,  0.000,  0.000]

system2.atoms ->
     id |   atype |  pos[0] |  pos[1] |  pos[2]
      0 |       1 |   0.000 |   0.000 |   0.000
      1 |       1 |   2.825 |   0.000 |   2.825
      2 |       1 |   2.825 |   2.825 |   0.000
      3 |       1 |   0.000 |   2.825 |   2.825
      4 |       2 |   1.413 |   1.413 |   1.413
      5 |       2 |   4.237 |   4.237 |   1.413
      6 |       2 |   1.413 |   4.237 |   4.237
      7 |       2 |   4.237 |   1.413 |   4.237

system2.atoms_prop(key='velocity') ->
[[ 0.5035316   0.80137525  0.66409675]
 [ 0.51198465  0.70337495  0.35930918]
 [ 0.62085464  0.57660292  0.70785976]
 [ 0.02579449  0.57026407  0.35535985]
 [ 0.70334483  0.88415116  0.04908425]
 [ 0.77001756  0.37255959  0.47236711]
 [ 0.45937527  0.30354763  0.7853149 ]
 [ 0.62603152  0.4274895   0.66183075]]


__File Cleanup__

In [9]:
os.remove('test.data')