# AtomMan System Class

**Lucas M. Hale**, [lucas.hale@nist.gov](mailto:lucas.hale@nist.gov?Subject=ipr-demo), *Materials Science and Engineering Division, NIST*.

**Chandler A. Becker**, [chandler.becker@nist.gov](mailto:chandler.becker@nist.gov?Subject=ipr-demo), *Materials Science and Engineering Division, NIST*.

**Zachary T. Trautt**, [zachary.trautt@nist.gov](mailto:zachary.trautt@nist.gov?Subject=ipr-demo), *Materials Measurement Science Division, NIST*.

Version: 2016-03-31

[Disclaimers](http://www.nist.gov/public_affairs/disclaimer.cfm)

Return to the [main atomman page](https://github.com/usnistgov/atomman).

## Introduction

Class System represents a full atomistic system by combining an [Atoms](https://github.com/usnistgov/atomman/blob/master/atomman/core/Atoms.py) instance with a [Box](https://github.com/usnistgov/atomman/blob/master/atomman/core/Box.py) instance.  All of the methods of Atoms and Box have corresponding methods in System that add in functionality associated with coupling the atomic positions to the box geometry.  This includes the handling of periodic boundaries.

The underlying code can be found in [atomman/core/System.py](https://github.com/usnistgov/atomman/blob/master/atomman/core/System.py).

__Library Imports__

In [1]:
#Standard library imports
from collections import OrderedDict

#External library imports
import numpy as np

#atomman imports
from atomman import Atoms, Box, System

## 1.  Initilization

Initilizing a System has the following optional arguments:

- __atoms__ = an Atoms instance.  The default value is to initilize an Atoms instance with Atoms().

- __box__ = a Box instance. The default value is to initilize a Box instance with Box().

- __pbc__ = a list of three boolean values where True indicates that the corresponding dimension is periodic.  The default value is (True, True, True).

- __scale__ = boolean indicating that the pos contained in atoms should be treated as relative to the box dimensions.  If True, the pos values will be multiplied by the box vectors to obtain absolute position values.  The default value is False.

- __prop__ = a dictionary allowing for system properties to be saved with the System object.  The default value is an empty dictionary.

For the built-in scaling functionality, ahe atomic positions stored in a System's atoms should be in absolute values, not box scaled values.

__Note:__ The number of atoms in a System is fixed because the number of atoms in the contained Atoms instance is fixed.   

In [2]:
#Create a system for a fcc unit cell with a=3.2
atoms = Atoms(natoms=4)
atoms.prop(key='atype', value=[1])
atoms.prop(key='pos', value=np.array([[0.0, 0.0, 0.0],
                                      [0.5, 0.5, 0.0],
                                      [0.5, 0.0, 0.5],
                                      [0.0, 0.5, 0.5]]))
box = Box(a=3.2, b=3.2, c=3.2)

system1 = System(atoms=atoms, box=box, scale=True)

## 2. Atoms-based methods and attributes

The underlying Atoms instance can be directly accessed with System.atoms.  All of the attributes and methods for Atoms can then be directly accessed in this fashion.  

Additionally, a number of system-wide methods and attributes are defined to extend functionality.

### 2.1 System.atoms_prop()

The System.atoms_prop() method corresponds to the Atoms.prop() method and adds an optional scale argument.  If scale is True, then the value being set or returned with the method is scaled or unscaled using the Box vectors. The default value of scale is False.

In [3]:
#No arguments returns list of assigned properties
print "system1.atoms_prop() ->", system1.atoms_prop()
print

#Without scale, atoms_prop is identical to Atoms.prop()
print "system1.atoms_prop(key='pos') ->"
print system1.atoms_prop(key='pos')
print

#scale=True scales relative to box vectors
print "system1.atoms_prop(key='pos', scale=True) ->"
print system1.atoms_prop(key='pos', scale=True)
print

#Set 1, pos using scale
system1.atoms_prop(a_id=1, key='pos', value=[0.25, 0.25, 0.25], scale=True)
print "system1.atoms_prop(a_id=1, key='pos', value=[0.25, 0.25, 0.25], scale=True)"
print "system1.atoms_prop(a_id=1, key='pos') ->", system1.atoms_prop(a_id=1, key='pos')
print "system1.atoms_prop(a_id=1, key='pos', scale=True) ->", system1.atoms_prop(a_id=1, key='pos', scale=True)
print 

#Set 1, pos not using scale
system1.atoms_prop(a_id=1, key='pos', value=[1.6, 1.6, 0.0])
print "system1.atoms_prop(a_id=1, key='pos', value=[1.6, 1.6, 0.0])"
print "system1.atoms_prop(a_id=1, key='pos') ->", system1.atoms_prop(a_id=1, key='pos')
print "system1.atoms_prop(a_id=1, key='pos', scale=True) ->", system1.atoms_prop(a_id=1, key='pos', scale=True)

system1.atoms_prop() -> ['atype', 'pos']

system1.atoms_prop(key='pos') ->
[[ 0.   0.   0. ]
 [ 1.6  1.6  0. ]
 [ 1.6  0.   1.6]
 [ 0.   1.6  1.6]]

system1.atoms_prop(key='pos', scale=True) ->
[[ 0.   0.   0. ]
 [ 0.5  0.5  0. ]
 [ 0.5  0.   0.5]
 [ 0.   0.5  0.5]]

system1.atoms_prop(a_id=1, key='pos', value=[0.25, 0.25, 0.25], scale=True)
system1.atoms_prop(a_id=1, key='pos') -> [ 0.8  0.8  0.8]
system1.atoms_prop(a_id=1, key='pos', scale=True) -> [ 0.25  0.25  0.25]

system1.atoms_prop(a_id=1, key='pos', value=[1.6, 1.6, 0.0])
system1.atoms_prop(a_id=1, key='pos') -> [ 1.6  1.6  0. ]
system1.atoms_prop(a_id=1, key='pos', scale=True) -> [ 0.5  0.5  0. ]


### 2.2 System.natoms and System.natypes

These two System attributes are identical to their Atoms counterparts.

In [4]:
print "system1.natoms ->", system1.natoms
print "system1.natypes ->", system1.natypes

system1.natoms -> 4
system1.natypes -> 1


## 3. Box-based methods and attributes

The underlying Box instance can be directly accessed with System.box.  All of the attributes and methods for a Box can then be directly accessed in this fashion.  

Additionally, a number of system-wide methods and attributes are defined to extend functionality.

### 3.1 System.box_set()

The System.box_set() method corresponds to the Box.set() method.  The only difference is that System.box_set() has a scale argument.  With scale=False, the box vectors will be changed and the atoms left in their current positions.  With scale=True, the atoms will also be displaced such that their positions remain proportional to the box.

In [5]:
system1.box_set(a=4, b=4, c=4, scale=True)
print "system1.box_set(a=4, b=4, c=4, scale=True)"
print "system1.box ->"
print system1.box
print "system1.atoms ->"
print system1.atoms
print 

system1.box_set(a=3, b=3, c=3)
print "system1.box_set(a=4, b=4, c=4)"
print "system1.box ->"
print system1.box
print "system1.atoms ->"
print system1.atoms
print

system1.box_set(a=4, b=4, c=4)
system1.box_set(a=3.2, b=3.2, c=3.2, scale=True)
print "system1.box_set(a=4, b=4, c=4)"
print "system1.box_set(a=3.2, b=3.2, c=3.2, scale=True)"
print "system1.box ->"
print system1.box
print "system1.atoms ->"
print system1.atoms

system1.box_set(a=4, b=4, c=4, scale=True)
system1.box ->
avect =  [ 4.000,  0.000,  0.000]
bvect =  [ 0.000,  4.000,  0.000]
cvect =  [ 0.000,  0.000,  4.000]
origin = [ 0.000,  0.000,  0.000]
system1.atoms ->
     id |   atype |  pos[0] |  pos[1] |  pos[2]
      0 |       1 |   0.000 |   0.000 |   0.000
      1 |       1 |   2.000 |   2.000 |   0.000
      2 |       1 |   2.000 |   0.000 |   2.000
      3 |       1 |   0.000 |   2.000 |   2.000

system1.box_set(a=4, b=4, c=4)
system1.box ->
avect =  [ 3.000,  0.000,  0.000]
bvect =  [ 0.000,  3.000,  0.000]
cvect =  [ 0.000,  0.000,  3.000]
origin = [ 0.000,  0.000,  0.000]
system1.atoms ->
     id |   atype |  pos[0] |  pos[1] |  pos[2]
      0 |       1 |   0.000 |   0.000 |   0.000
      1 |       1 |   2.000 |   2.000 |   0.000
      2 |       1 |   2.000 |   0.000 |   2.000
      3 |       1 |   0.000 |   2.000 |   2.000

system1.box_set(a=4, b=4, c=4)
system1.box_set(a=3.2, b=3.2, c=3.2, scale=True)
system1.box ->
avect =  [ 3.

### 3.4 System.box_normalize()

The System.box_normalize() method normalizes the box vectors to be compatible with LAMMPS.  In doing so, the System's atom positions will also be changed such that the configurations remain identical.

### 4. Unique System methods

Additional methods of the System depend on both the Atoms and the Box as well as the periodic boundary conditions.

### 4.1 System.pbc

System.pbc defines the periodic boundary conditions.  Values of True indicate that the associated dimension is periodic.

In [6]:
#No arguments returns a copy of pbc
print "system1.pbc ->", system1.pbc
print

#The values can be changed by supplying a list of booleans
system1.pbc = [True, False, True]
print "system1.pbc = [True, False, True]"
print "system1.pbc ->", system1.pbc
print

#Integers allow for index access of pbc
print "system1.pbc[0] ->", system1.pbc[0]
print "system1.pbc[1] ->", system1.pbc[1]
print "system1.pbc[2] ->", system1.pbc[2]

system1.pbc -> [ True  True  True]

system1.pbc = [True, False, True]
system1.pbc -> [ True False  True]

system1.pbc[0] -> True
system1.pbc[1] -> False
system1.pbc[2] -> True


### 4.2 System.scale() and System.unscale()

System.scale() converts three-dimensional vectors from absolute coordinates to box-scaled coordinates.  System.unscale() converts three-dimensional vectors from box-scaled coordinates to absolute coordinates.

In [7]:
pos = system1.atoms_prop(key='pos')
print "pos = system1.atoms_prop(key='pos')"
print "pos ->"
print pos
print 

spos = system1.scale(pos)
print "spos = system1.scale(pos)"
print "spos ->"
print spos
print 

print "system1.unscale(spos) ->"
print system1.unscale(spos)

pos = system1.atoms_prop(key='pos')
pos ->
[[ 0.   0.   0. ]
 [ 1.6  1.6  0. ]
 [ 1.6  0.   1.6]
 [ 0.   1.6  1.6]]

spos = system1.scale(pos)
spos ->
[[ 0.   0.   0. ]
 [ 0.5  0.5  0. ]
 [ 0.5  0.   0.5]
 [ 0.   0.5  0.5]]

system1.unscale(spos) ->
[[ 0.   0.   0. ]
 [ 1.6  1.6  0. ]
 [ 1.6  0.   1.6]
 [ 0.   1.6  1.6]]


### 4.3 System.dvect()

System.dvect() identifies the shortest vector between two points (or lists of points) in space taking the periodic boundary information of the System into consideration.  Integer arguments can also be used in which case the pos of the atoms corresponding to those indices are used.

In [8]:
#using dvect with integers
print "Vector between atoms 0 and 1:"
print "system1.dvect(0,1) ->", system1.dvect(0,1)
print 

#using dvect with a specified point
print "Difference between [1.6, 1.6, 1.6] and all atoms:"
print "system1.dvect([1.6, 1.6, 1.6], system1.atoms_prop('pos')) ->"
print system1.dvect([1.6, 1.6, 1.6], system1.atoms_prop(key='pos'))
print 

print "Same thing using list of integers:"
print "system1.dvect([1.6, 1.6, 1.6], (0,1,2,3)) ->"
print system1.dvect([1.6, 1.6, 1.6], (0,1,2,3))

Vector between atoms 0 and 1:
system1.dvect(0,1) -> [ 1.6  1.6  0. ]

Difference between [1.6, 1.6, 1.6] and all atoms:
system1.dvect([1.6, 1.6, 1.6], system1.atoms_prop('pos')) ->
[[-1.6 -1.6 -1.6]
 [ 0.   0.  -1.6]
 [ 0.  -1.6  0. ]
 [-1.6  0.   0. ]]

Same thing using list of integers:
system1.dvect([1.6, 1.6, 1.6], (0,1,2,3)) ->
[[-1.6 -1.6 -1.6]
 [ 0.   0.  -1.6]
 [ 0.  -1.6  0. ]
 [-1.6  0.   0. ]]


### 4.4 System.wrap()

System.wrap() fixes the system such that no atoms lie outside the box.  This is accomplished by wrapping the outlying atoms around periodic boundaries, and then extending any non-periodic boundaries. 

In [9]:
print "Move atom 0 outside the box boundaries:"
system1.atoms_prop(a_id=0, key='pos', value=[-1.,-1.,-1.])
print "system1.atoms_prop(a_id=0, key='pos', value=[-1.,-1.,-1.])"
print "system1.pbc ->", system1.pbc
print "system1.box ->"
print system1.box
print "system1.atoms ->"
print system1.atoms
print 

print "Wrap atoms and extend boundaries"
system1.wrap()
print "system1.wrap()"
print "system1.pbc ->", system1.pbc
print "system1.box ->"
print system1.box
print "system1.atoms ->"
print system1.atoms
print 

Move atom 0 outside the box boundaries:
system1.atoms_prop(a_id=0, key='pos', value=[-1.,-1.,-1.])
system1.pbc -> [ True False  True]
system1.box ->
avect =  [ 3.200,  0.000,  0.000]
bvect =  [ 0.000,  3.200,  0.000]
cvect =  [ 0.000,  0.000,  3.200]
origin = [ 0.000,  0.000,  0.000]
system1.atoms ->
     id |   atype |  pos[0] |  pos[1] |  pos[2]
      0 |       1 |  -1.000 |  -1.000 |  -1.000
      1 |       1 |   1.600 |   1.600 |   0.000
      2 |       1 |   1.600 |   0.000 |   1.600
      3 |       1 |   0.000 |   1.600 |   1.600

Wrap atoms and extend boundaries
system1.wrap()
system1.pbc -> [ True False  True]
system1.box ->
avect =  [ 3.200,  0.000,  0.000]
bvect =  [ 0.000,  4.203,  0.000]
cvect =  [ 0.000,  0.000,  3.200]
origin = [ 0.000, -1.003,  0.000]
system1.atoms ->
     id |   atype |  pos[0] |  pos[1] |  pos[2]
      0 |       1 |   2.200 |  -1.000 |   2.200
      1 |       1 |   1.600 |   1.600 |   0.000
      2 |       1 |   1.600 |   0.000 |   1.600
      3 |     